### ISSUE TITLE
Hello, I need help.

### ISSUE THREAD

**Issue by cosmokid** [taixhi/wordblitz#1]
Every time I enter anything I get this error:

`Traceback (most recent call last):
  File "generator.py", line 65, in <module>
    board = create_board(input)
  File "generator.py", line 56, in create_board
    [input[12], input[13], input[14], input[15]]]
IndexError: string index out of range`

**Comment by taixhi** [comment]
you need to input 16 characters for it to work (since wordblitz has 4x4=16 characters)
